### ISSUE TITLE
wav format

### ISSUE THREAD

**Issue by marcomiguel** [kravets-levko/pretty-file-icons#2]
Levko, please.
Do you can you add icons for video files: mp2, mxf and audio files: wav.

Regards.

**Comment by kravets-levko** [comment]
Hi @tresemece! I'll try to do all possible, and will notify you when new icons will be available.

**Comment by kravets-levko** [comment]
@tresemece, new version is already on npm, live preview also updated.

**Comment by marcomiguel** [comment]
Thanks! @kravets-levko
